### PR TITLE
feat: updates for Electron 10

### PR DESCRIPTION
**Pull request by evereq**

### CODE REVIEW

**Comment by sindresorhus** [comment]
You need to update the JS file and readme too.

**Comment by evereq** [comment]
@sindresorhus what exactly should be updated there? In Readme, I can't found anything related to the version of Electron (sorry if missed something), and in JS files I also not sure what is needed to be changed? 
We only removed type usage that was removed from Electron 10...  
If you can provide any hints, we will be glad to update PR.

CC: @syns2191

**Comment by sindresorhus** [comment]
The types changed because the API changed. I would recommend reading the Electron 10 release notes.

**Comment by sindresorhus** [comment]
Closing in favor of #36

**Pull request closed without merging**
